version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/docker/dev.Dockerfile
    restart: always
    volumes:
      - ./apps/web/src:/app/apps/web/src
      - ./packages/ui:/app/packages/ui
      - /apps/web/node_modules
      - /apps/web/.next
    ports:
      - 3000:3000
    networks:
      - app_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/docker/dev.Dockerfile
    restart: always
    volumes:
      - ./apps/api/src:/app/apps/api/src
    ports:
      - 3001:3001
    networks:
      - app_network

networks:
  app_network:
